### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by vigilancetrent** [rizki4106/netrade#7]
Traceback (most recent call last):
  File "C:/Users/bill/Desktop/teemaki/ai netrade/ai.py", line 90, in <module>
    model, history = netrade.train(X_train=dataloader,X_test=dataloader , epochs=10)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python310\lib\site-packages\netrade\core.py", line 57, in train
    accuracy_score = Accuracy().to(device)
TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'

**Comment by 32dantey** [comment]
I tried changing this task problem in the code to MULTILABEL and MULTICLASS and BINARY to no resolve.
